#!/bin/ash

set -eu

cp target/librust_example.a ruby/ext/rust_example/librust_example.a
(
  cd ruby/ext/rust_example;
  echo "ruby extconf.rb";
  ruby extconf.rb;
  echo "make clean";
  make clean;
  echo "make";
  make
)
echo
echo "Testing"
(cd ruby; ruby -Ilib:ext -r rust_example -e "RustExample.hello")
