#!/bin/ash

set -eu

cp target/librustimpl.so ruby/ext/rust_example/librustimpl.so
(
  cd ruby/ext/rust_example;
  echo "$ ruby extconf.rb";
  ruby extconf.rb;
  echo "$ make clean";
  make clean;
  echo "$ make";
  make
)
echo
echo "Testing"
(cd ruby; ruby -Ilib:ext -r rust_example -e "RustExample.hello")
